### ISSUE TITLE
Wrong licenseplate formatting for npc (en language)

### ISSUE THREAD

**Issue by creator2013** [GuillaumeBenit/LicensePlate#4]
It should be 
```
return LicensePlate_let(ply,1).."▓ - "..LicensePlate_id(ply).. " - ▓".. LicensePlate_let(ply,10)
```
and not 
```
"▓"..LicensePlate_let(ply,1)..LicensePlate_let(ply,10).."▓"..LicensePlate_id(ply)
```

**Comment by GuillaumeBenit** [comment]
Why ?

**Comment by creator2013** [comment]
Set your language to en and compare the plate from your car with the one from the cardealer.

**Comment by GuillaumeBenit** [comment]
There is no problem. 
![20161222201051_1](https://cloud.githubusercontent.com/assets/8426775/21437215/de15e926-c882-11e6-9778-42d4a3f43fa1.jpg)

**Comment by creator2013** [comment]
The formatting was different on my server. Wait I will send a screenshot

//EDIT
![rp_chaos_city_v33x_030004](https://cloud.githubusercontent.com/assets/20265555/21437499/6d1c4272-c884-11e6-8b02-582d26544afe.jpg)

**Comment by GuillaumeBenit** [comment]
Have you got restart your server ? Because the text of the license plate is the french text.

**Comment by creator2013** [comment]
Wait...... I think I know the problem: The cvar is still frensh but my client language is on United States
